#! /bin/bash

function checkFileExist()
{
    for currentFile in $(awk '{print $1}' ~/Documents/Annuaires/.files | sort -u)
    do
        if [[ $1 = $currentFile ]];then
            echo 0
        fi
    done  
    exit 1          
}

user=$(whoami)
SUFFIX_ANNUAIRE_FILE="/home/$user/Documents/Annuaires/"


case $# in
    1)
        while getopts "f" option; do
        done              
    ;;
    2|3)
        while getopts "tTMdmg:aes:b:hc:" option; do
        done
    ;;
    *)
        echo annuaire -option {argument} annuaireFile
    ;;
esac